name: C2SIM Problem Report / Change Request
description: Please use this template to create a new C2SIM issue.
title: "[C2SIM Issue]: "
labels: ["issue", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: WIs this a Problem report or a change request
      options:
        - Problem Report
        - Change Request
    validations:
      required: true
   - type: input
